name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: '2.x'
      - name: Run tests
        run: deno test
